Repository khannakshat7/Elektra, pull requests merged in 2021-04, with the labels that each got.

#136 Added recaptcha to contact form issue(#124)
  electricity/views.py
  templates/base.html
  templates/contact.html
  templates/login.html
Labels: Level3, enhancement, gssoc21

#155 [Gssoc'21] Added the 404 page to website with 404 handling code
  Elecktra/urls.py
  electricity/views.py
  templates/404.html
Labels: Level3, good first issue, gssoc21

#161 [Gssoc'21] Added the show password feature
  static/main.js
  static/showpassword.js
  templates/login.html
Labels: Level3, good first issue, gssoc21

#171 added username and email checking in front end
  Elecktra/urls.py
  electricity/views.py
  templates/login.html
Labels: Level3, enhancement, gssoc21

#162 Tweaks made in the Contact.html with reference with issue assigned to me #159
  electricity/views.py
  templates/contact.html
Labels: Level3, bug, gssoc21

#179 Dashboard view issue
  static/style.css
Labels: Level2, good first issue, gssoc21

#180 Added a confirmation alert before logout
  templates/base.html
  templates/dashboard.html
Labels: Level3, enhancement, good first issue, gssoc21
