Repository khannakshat7/Elektra, pull requests merged in 2021-05, with the labels that each got.

#172 Fixed the bug in Feedback and Added the Backend for it
  electricity/models.py
  electricity/views.py
  templates/feedback.html
Labels: Level3, gssoc21

#192 Added the Back to top button
  templates/base.html
Labels: Level3, gssoc21

#196 Add error/success flash message on reset password and some passwords validations
  electricity/views.py
  templates/forgotpassword.html
  templates/otp.html
  templates/resetpassword.html
Labels: Level3, gssoc21

#194 added dark mode to the website
  static/darkmode.js
  static/style.css
  templates/announcements.html
  templates/base.html
  templates/contact.html
  templates/feedback.html
Labels: Level3, gssoc21

#199 password validations and exception handling
  electricity/views.py
  templates/resetpassword.html
Labels: Level3, bug, gssoc21

#200 added darkmode to dashboard , cards and navbar
  templates/base.html
  templates/dashboard.html
Labels: Level3, bug, gssoc21

#204 Feedback model is not registered in admin.py
  electricity/admin.py
Labels: Level3, bug, good first issue, gssoc21

#202 addded show password feature in password reset
  templates/resetpassword.html
Labels: Level3, enhancement, gssoc21

#132 fixed the misplaced forgot password
  templates/login.html
Labels: Level3, good first issue, gssoc21

#211 fixed the bug the toggle was not visible in mobile screen
  templates/dashboard.html
Labels: Level2, bug, gssoc21

#210 change username to firs name in dashboard like otherpages
  templates/dashboard.html
Labels: Level2, good first issue, gssoc21

#218 done eslint setup and added prettier
  static/.eslintrc.json
  static/darkmode.js
  static/main.js
  static/showpassword.js
Labels: Level3, good first issue, gssoc21

#212 Email warning if login fails more than 5 times
  electricity/views.py
Labels: Level3, gssoc21

#221 fixed a bug in email warning feature
  electricity/views.py
Labels: Level3, bug, gssoc21

#225 documentation on ESlint setup
  docs/ESlint-Setup.md
  electricity/views.py
Labels: Level3, gssoc21

#217 improving buttons in every page
  templates/contact.html
  templates/feedback.html
  templates/forgotpassword.html
  templates/index.html
  templates/login.html
  templates/map.html
  templates/otp.html
Labels: Level3, gssoc21

#216 navbar
  static/style.css
  templates/base.html
Labels: Level3, gssoc21

#226 change password feature
  Elecktra/urls.py
  electricity/views.py
  templates/base.html
  templates/changePassword.html
Labels: Level3, enhancement, gssoc21

#229 added password validations and current password field
  electricity/views.py
  templates/changePassword.html
Labels: Level3, enhancement, gssoc21

#230 added a video link in read me for project set up
  README.md
Labels: Level3, good first issue, gssoc21

#131 Footer
  templates/base.html
Labels: Level3, enhancement, gssoc21

#234 added showPassword feature in changePassword page
  Elecktra/urls.py
  templates/changePassword.html
Labels: Level3, enhancement, good first issue, gssoc21

#232 added required in both fields of login and double checked all other input fields
  templates/login.html
Labels: Level3, bug, good first issue, gssoc21

#141 #2-Acknowledging the user with future outrages : Worked on remote repo and modified it.#settings.py is also changed
  Elecktra/settings.py
  electricity/views.py
  templates/feedback.html
Labels: Level3, gssoc21

#241 added a confirmation email after changing password
  electricity/views.py
Labels: Level3, enhancement, good first issue, gssoc21

#238 added download csv feature for contact and elecktricity
  electricity/admin.py
Labels: Level3, gssoc21

#236 Card
  templates/contact.html
  templates/forgotpassword.html
  templates/login.html
Labels: Level3, gssoc21

#242 added github bot feature
  .github/workflows/automessage_on_prs.yml
Labels: Level2, gssoc21
