Repository khannakshat7/Elektra, pull requests merged in 2021-03, with the labels that each got.

#39 Redirection issue of the logged in user.
  electricity/views.py
Labels: Level2, bug, gssoc21

#40 Feedback form bug
  templates/feedback.html
Labels: Level2, bug, gssoc21

#48 Added highlight active page in navbar
  static/style.css
  templates/base.html
  templates/dashboard.html
Labels: Level2, bug, gssoc21

#75 Login and Registration Form
  Elecktra/urls.py
  electricity/forms.py
  electricity/models.py
  electricity/views.py
  templates/forgotpassword.html
  templates/login.html
Labels: Level3, enhancement, gssoc21

#89 Bug in base.html
  templates/base.html
Labels: Level2, gssoc21

#88 Fixed Unequal card heights
  templates/index.html
Labels: Level2, bug, gssoc21

#104 Bug resolved in preloader
  static/style.css
  templates/base.html
Labels: Level2, enhancement, gssoc21

#121 Social auth
  Elecktra/settings.py
  Elecktra/urls.py
  requirements.txt
  static/google.png
  templates/login.html
Labels: Level3, enhancement, gssoc21

#69 Added Contact Page
  Elecktra/settings.py
  Elecktra/urls.py
  electricity/admin.py
  electricity/models.py
  electricity/views.py
  static/rocket_contact.png
  templates/base.html
  templates/contact.html
Labels: Level3, enhancement, gssoc21

#90 Shrink the nav-menu to right
  static/style.css
Labels: Level2, enhancement, gssoc21

#125 [GSSoC'21] Fixes the Responsiveness of map page
  templates/base.html
Labels: Level2, bug, gssoc21

#135 [Gssoc'21] Added the Password validations in front-end
  templates/login.html
Labels: Level3, good first issue, gssoc21
